package main

import (
	"fmt"
	"sort"
)

func main() {

	fmt.Println(rankTeams([]string{"ABC", "ACB", "ABC", "ACB", "ACB"}))
	fmt.Println(rankTeams([]string{"WXYZ", "XYZW"}))
	fmt.Println(rankTeams([]string{"ZMNAGUEDSJYLBOPHRQICWFXTVK"}))
	fmt.Println(rankTeams([]string{"BCA", "CAB", "CBA", "ABC", "ACB", "BAC"}))
	fmt.Println(rankTeams([]string{"M", "M", "M", "M"}))
	fmt.Println(rankTeams([]string{"FVSHJIEMNGYPTQOURLWCZKAX", "AITFQORCEHPVJMXGKSLNZWUY", "OTERVXFZUMHNIYSCQAWGPKJL", "VMSERIJYLZNWCPQTOKFUHAXG", "VNHOZWKQCEFYPSGLAMXJIUTR", "ANPHQIJMXCWOSKTYGULFVERZ", "RFYUXJEWCKQOMGATHZVILNSP", "SCPYUMQJTVEXKRNLIOWGHAFZ", "VIKTSJCEYQGLOMPZWAHFXURN", "SVJICLXKHQZTFWNPYRGMEUAO", "JRCTHYKIGSXPOZLUQAVNEWFM", "NGMSWJITREHFZVQCUKXYAPOL", "WUXJOQKGNSYLHEZAFIPMRCVT", "PKYQIOLXFCRGHZNAMJVUTWES", "FERSGNMJVZXWAYLIKCPUQHTO", "HPLRIUQMTSGYJVAXWNOCZEKF", "JUVWPTEGCOFYSKXNRMHQALIZ", "MWPIAZCNSLEYRTHFKQXUOVGJ", "EZXLUNFVCMORSIWKTYHJAQPG", "HRQNLTKJFIEGMCSXAZPYOVUW", "LOHXVYGWRIJMCPSQENUAKTZF", "XKUTWPRGHOAQFLVYMJSNEIZC", "WTCRQMVKPHOSLGAXZUEFYNJI"}))

	fmt.Println(rankTeams([]string{"XDELQOKZUGMCBTWAJNPFRVIS", "IQKGUDCWMNLSABZEPVXFJRTO", "SFPUJWZABNRLQEMXKIGDVCTO", "FISQWOZAGXJDNLTKPRECVUBM", "BMXIRQOWJSLPDNGAEFKZTUVC", "SCUFTIAQMWNXBGZEOJVDLKRP", "LMNXWKDBTAGPFUCJSROIQZEV", "NVDICPQFBZLRGWTMXJOAUESK", "PGZRUWNFMKTVJSLCDEXOABIQ", "BFKNDXRIGWTVSUJOCMPZAEQL", "MJLDKRNWPQXUFSTEGCOBVAIZ", "VCIMLFJSPZTDRKBAGXWUOEQN", "TERGMVDPILNQSFJCAKZWXBOU", "KOPFCIDQSVAMRBLNTWUZXJGE", "NKWPJGUAFOTZIERXMSLBDCQV", "QUKLSIFCDVZEAMXGJNTWROPB", "DSAGZRFWTMJEILKOPUNQVXCB", "ARQIVZNCMBJGWUPKEOSLFTDX", "ESMATLNJKPRFGXWVUCOQDIZB", "QNGTVDFICPSKMWUJBOZELAXR", "JAOMTSGFQPDWKRNLUXEVBCIZ", "FORAQBEDSTNPUZICVXGWMKLJ", "UWAFSXITRMPEGVQDLZBCNJOK", "IKFOVMNWJLCZBUAGERQPXTSD", "SLEOPWNDBUVIGQJZMRACXTFK", "GTDKMOJSILNAVXFPZQCUWRBE", "AZGRVFJDEUSCNLTBXWQIPMOK", "VQPNUMCJKSBXWIAFTGDOEZRL", "PVNODUXIMJSGACQTWRFBKLZE", "QGKDUAIMEVTXSZFBJLOWNPRC", "MDUOXBVQJPSAGNIKLRFZTCWE", "FMRTEDKWPVLGBICXSNZAQJOU", "WUEFMGXSIRNAOPCBDLQTKJZV", "UDGSPEQVZOBMNICJKXTWALRF", "SFNWLTARVKPJQZMGUDBOICEX", "FSPCMAJZEKNRLDWBGOXQIUVT", "VRUOAMJQGFSIZNXLEPWTDCBK", "VNCMBRLKUPDISJEWOAZGTXFQ", "VGJQZXMPKEIRLTNODCABWFSU", "IMALJVBCXSQPOUGEKNTRFDWZ", "UPJBVKQOAIDGWEZRLTNSXFMC", "IUAPCZFWOQTXBSNLKGVRDMEJ", "DOIRNGMKJLEUCPTWZQSVXFAB", "VJMWTPZFOGBNIDCQAULERKSX", "OAISKWCDLVRQFGNZPUTJEMXB", "NBTGWMEUROJDCKAZLFQXISPV", "DSOBAIJXFWNTUVERGQMCLKPZ", "SBLFZOGCNDWPXAEKTVRJUMIQ", "EKWMAQNURJBZPLFDSGOVIXCT", "BKXRSNVMWGAPCIFLZJTEUQOD", "VQNWJSZTCPEURAKBLIXOFGMD", "TQKFDXCWIUARVBELNOPJZGMS", "MSCPWBTKQUFVDGEXROANJLIZ", "XFQVITPRZMONWCLKBUAJGSED", "MVKLRFQWICOPDJBUSTXNEZGA", "DMKBRGLONJEIFTXZPUACQWSV", "NKSJBQZORVFTXWAUCDLGEMIP", "JQUIXNBRDMOLGSTFVAZCPEWK", "MEBXTJUNVWCQAZGRLIKSPDFO", "EKNUQILMTDPOSFJZWXGVCARB", "JOZNFECPVSXRLGDUKQWBITAM", "UXNZISEGTCVABJMKFLWDQPOR", "IJCFLPGZRXQUMANODKBVSETW", "KCJQRFEWNGAMBIXZVLPDSUTO", "TMSEDRAUWZGQXJPIFVLCOBKN", "ZPRXJNOEKCGFUSDQAILWMVTB", "WTBXANSJLRKFEPOIVDMQUZCG", "IRLVZNQPECOJATFWUSDMGKBX", "BGMPAZOIKWCSUDJNXLTVREQF", "BZXSTPRMLEKWCFIVONGADUQJ", "UFGZCWTARKSBDJXPMVQIENOL", "ZBROLDUFMNQAPJEGITXWCSKV", "FWLJXQDTRCGNVUZMAPBKISEO", "SJXLKAVZCPBIEWFQTNODGRMU", "VAIBDLOEXGUZQWMPNSJTCRKF", "XFLMPECKOQINGWSZJRTVBADU", "ZAJCPMSKUBFWEXQDTVGNLORI", "FUVECNMKZWJBGXTDLPASIOQR", "COFKSVMTNLBWXAREZDQIJUGP", "TKRVFXUIONEALPCDSJGBZWQM", "VJNQLTARZSGCPOMFBUWIXKDE", "GMUSFBPDZATKWEQONXCJILVR", "RFNCLTQZXMSVWPIUBGDEAKOJ", "NARSWLXMEIGQCFBOVDUJPZTK", "OBZVJGSKDUCXAQWPIFNEMTRL", "RIEQDWFSLCGTPKNBAJUVMZOX", "GBAXDSVUEOJNTLPIRKZCWQMF", "ZOETNALWVPGXRIMQKDBFUSCJ", "NAMBJKFZQTOSGWCDPIRXLEUV", "NWQJUZMKIXCGDSBREFPATLOV", "KWAECTUZODSPIJMNLVQRXFBG", "JXPWZNOCGRDKLQITUSEVAFBM", "FNAXSLPRWUBMQJICZTVKDOEG", "GMAWSUXVPZINTODEBRJFKQLC", "FACUKTLWNJSXRQMEDZVGBOIP", "FXEGPVLUJDRNQMTOWSIKAZCB", "ZNEKOJXDVQSUFARMLWPGICTB", "IRSZQGUKVJXCANFWLOBDEMPT", "IUEDPRJFVGQSAXNOWCBMZTLK", "XGKLOPJVQCWTBMSNUZARIEDF", "VSOJUPRFDCNQXTLMBKIGZWEA", "UDGIKPAFNTZWCJRMSLVOXEQB", "GQOIULRNMCJVPFEAZBSDWKTX", "ZJUTMKIFXRSCOPENVGLBDAQW", "ZUQOBCPWNJKVARLTDEGIXFSM", "ADBOKTGCWFMNVUEZLRPIQJSX", "ALDVEQZKCTOJRWBMISPNXFGU", "CEGUFDRXLAVTQNWOKMPZIJBS", "EMBXCVQDJLNWSGIZPRAFTUKO", "KJSQEPNOVGRWZLUIADFBCTXM", "UWVFQEDASJBGXCNPTZIORMLK", "XFLCZSMJAVEPIQDRTUBNKGWO", "URFBQMVATJWEPDCNGSILOZXK", "ZLDPUVIWOJEXGNTQFRBKSACM", "IEQBVDUPNLCGJASFRXTWZOMK", "TVWMROKSUPCXNFEALDQZIGBJ", "GFKEZOICNTXPASMBJVRUWLDQ", "NVWKLBMQJFPIRCSDOZGTXEAU", "QANRCGLPMDZKFOTXBVJEIWUS", "UPCLXNVQZTRKMEBGAOSFDJWI", "PANMJZIFCWGKQDXSRUETOLVB", "JGWVNUXLKAEODTBZIQRCMPFS", "TEOMUIZFSXPGWLADRBQKJVCN", "XPFDJLGZAWEKTRVCMBNUSOQI", "OCQSTRKAZPIMUBNDGEXJVWLF", "MILWTBRAVGZODFJUCSPXQENK", "FREBOSZDPMCNUJXAVKIGLWQT", "TQWPUCERNGIBMXDZKJVASFOL", "APLDRMWCQNFUTSKXVEGJIZBO", "SUWEMPJNFITABXVOCRZLDQKG", "FGRZBWMUTIACNEJKVQPXDOSL", "PBUWQEIDOLXCRNFVSZJTKAMG", "BRFZUGVLWEJKNIASPMTXDQOC", "XLIPMTZQSUFVANKOGBEJDRCW", "GSCRPUAKMEIDBVOLQXWZNFTJ", "KCQMJXRWSFGNBDLAUOTEIVZP", "GKDPJSRMALVEXUNWOICTFQZB"}))
}

func rankTeams(votes []string) string {
	if len(votes) == 0 {
		return ""
	}
	var ranks [26][]int
	maxRank := len(votes[0])

	for _, vote := range votes {
		for ix := range vote {
			if len(ranks[getIx(vote[ix])]) == 0 {
				ranks[getIx(vote[ix])] = make([]int, maxRank)
			}
			ranks[getIx(vote[ix])][ix]++
		}
	}

	//fmt.Println(maxRank, ranks)
	//fmt.Println(maxRank)
	//fmt.Println(ranks[getIx('F')], ranks[getIx('U')])

	type pair struct {
		char  string
		votes []int
	}
	var pairs []*pair

	for ix, rank := range ranks {
		if len(rank) == 0 {
			continue
		}

		pairs = append(pairs, &pair{char: string('A' + ix), votes: rank})
	}

	sort.Slice(pairs, func(i, j int) bool {
		//fmt.Println(pairs[i].votes, " <? ", pairs[j].votes)
		for ix := range pairs[i].votes {
			//println("comparing", pairs[i].votes[ix], pairs[j].votes[ix])
			if pairs[i].votes[ix] == pairs[j].votes[ix] {
				continue
			}
			if pairs[i].votes[ix] < pairs[j].votes[ix] {
				//fmt.Printf("%s < %s\n", pairs[i].char, pairs[j].char)
				return true
			} else {
				return false
			}
		}
		//fmt.Printf("%s < %s\n", pairs[i].char, pairs[j].char)
		return pairs[i].char > pairs[j].char
	})

	var sol string
	for ix := len(pairs) - 1; ix >= 0; ix-- {
		sol += pairs[ix].char
	}

	return sol
}

func getIx(b byte) int {
	return int(b - 'A')
}
